### PR TITLE
Automatic binary release on GitHub

### PR DESCRIPTION
**Pull request by cecton**

### CODE REVIEW

**Comment by tjkirch** [comment]
This seems to mean we don't get changelog notes in the GitHub releases anymore - it'd be great to have a CHANGELOG file in lieu of that, if possible.

**Comment by cecton** [comment]
@tjkirch Those changelogs were made manually. I'm not sure how to make this automatic so I will probably continue doing it manually for now. (Also because there won't be much change in this library anymore).

I will complete all the missing logs in the GitHub releases and then I will push a copy in a CHANGELOG.md file soon.

**Comment by cecton** [comment]
@tjkirch fixed in 3537f41

**Comment by tjkirch** [comment]
Thank you, that's very helpful! And thanks for the great library!

**Pull request merged**
